import { Injectable } from '@angular/core';
import { RentalUnit, Room } from './unit.model';

@Injectable({ providedIn: 'root' })
export class Units {
  private readonly units: RentalUnit[] = [
    // ──────────────────────────────────────────────────────
    // AVALENA ROOMS
    // ──────────────────────────────────────────────────────
    {
      id: 'rooms',
      name: 'Avalena Rooms',
      taglineHr: 'Udobne sobe s balkonom u srcu Borika',
      taglineEn: 'Comfortable rooms with balconies in the heart of Borik',
      descriptionHr:
        'Šest kategorija soba — od kompaktnih dvokrevetnih do prostranijih četverokrevetnih — s drvenim podovima, balkonima i pogledom na grad.',
      descriptionEn:
        'Six room categories — from compact doubles to spacious quadruples — featuring hardwood floors, balconies and city views.',
      longDescriptionHr:
        'Avalena Rooms nudi raznovrsne smještajne kategorije prilagođene parovima, obiteljima i putnicima koji traže ugodan i funkcionalan boravak u Boriku. Sve sobe opremljene su klimom, ravnim TV ekranom, WiFi-jem, hladnjakom i privatnom kupaonicom. Prijava od 15:00, odjava do 10:00.',
      longDescriptionEn:
        'Avalena Rooms offers a variety of room categories suited to couples, families and travellers looking for a comfortable stay in Borik. All rooms feature air conditioning, flat-screen TV, WiFi, a fridge and a private bathroom. Check-in from 15:00, check-out by 10:00.',
      addressHr: 'Ul. Augusta Šenoe 22, Borik, Zadar',
      addressEn: 'Ul. Augusta Šenoe 22, Borik, Zadar',
      heroImage: '/images/rooms/684880052.jpg',
      gallery: [
        '/images/rooms/558049770.jpg',
        '/images/rooms/558689713.jpg',
        '/images/rooms/563273867.jpg',
        '/images/rooms/563539042.jpg',
      ],
      rooms: [
        {
          id: 'dvokrevetna-balkon',
          name: 'Dvokrevetna soba s bračnim krevetom i balkonom',
          nameEn: 'Double Room with Balcony',
          descriptionHr:
            'Soba od 22 m² s prostorom za sjedenje, TV ravnog ekrana, radnim stolom, balkonom i privatnom kupaonicom. Drveni pod.',
          descriptionEn:
            '22 m² room featuring a seating area with flat-screen TV, desk, balcony and private bathroom. Hardwood floor.',
          guests: 2,
          sizeM2: 22,
          hasBalcony: true,
          beds: [{ type: 'Veliki bračni krevet', count: 1 }],
          amenities: [
            'Balkon',
            'Klima uređaj',
            'Besplatni WiFi',
            'TV s ravnim ekranom',
            'Privatna kupaonica',
            'Hladnjak',
            'Radni stol',
            'Drveni pod',
            'Grijanje',
            'Električno kuhalo',
          ],
          amenitiesEn: [
            'Balcony',
            'Air conditioning',
            'Free WiFi',
            'Flat-screen TV',
            'Private bathroom',
            'Fridge',
            'Desk',
            'Hardwood floor',
            'Heating',
            'Electric kettle',
          ],
          heroImage: '/images/rooms/558049770.jpg',
          gallery: [
            'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?q=85&w=1200&auto=format&fit=crop',
            'https://images.unsplash.com/photo-1560185007-5f0bb1866cab?q=85&w=1200&auto=format&fit=crop',
            'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?q=85&w=1200&auto=format&fit=crop',
          ],
        },
        {
          id: 'dvokrevetna-budget',
          name: 'Niskobudžetna dvokrevetna soba s bračnim krevetom',
          nameEn: 'Budget Double Room',
          descriptionHr:
            'Kompaktna soba od 18 m² s prostorom za sjedenje, TV ravnog ekrana, radnim stolom, balkonom i privatnom kupaonicom.',
          descriptionEn:
            'Compact 18 m² room with seating area, flat-screen TV, desk, balcony and private bathroom.',
          guests: 2,
          sizeM2: 18,
          hasBalcony: true,
          beds: [{ type: 'Veliki bračni krevet', count: 1 }],
          amenities: [
            'Balkon',
            'Klima uređaj',
            'Besplatni WiFi',
            'TV s ravnim ekranom',
            'Privatna kupaonica',
            'Hladnjak',
            'Radni stol',
            'Drveni pod',
            'Grijanje',
          ],
          amenitiesEn: [
            'Balcony',
            'Air conditioning',
            'Free WiFi',
            'Flat-screen TV',
            'Private bathroom',
            'Fridge',
            'Desk',
            'Hardwood floor',
            'Heating',
          ],
          heroImage: '/images/rooms/558689713.jpg', //treba mjenjati sve
          gallery: [
            'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?q=85&w=1200&auto=format&fit=crop',
            'https://images.unsplash.com/photo-1566665797739-1674de7a421a?q=85&w=1200&auto=format&fit=crop',
          ],
        },
        {
          id: 'trokrevetna-balkon',
          name: 'Trokrevetna soba s balkonom',
          nameEn: 'Triple Room with Balcony',
          descriptionHr:
            'Prostrana soba od 30 m² s balkonom, prostorom za sjedenje, TV ravnog ekrana, radnim stolom i privatnom kupaonicom.',
          descriptionEn:
            'Spacious 30 m² room with balcony, seating area, flat-screen TV, desk and private bathroom.',
          guests: 3,
          sizeM2: 30,
          hasBalcony: true,
          beds: [
            { type: 'Veliki bračni krevet', count: 1 },
            { type: 'Krevet za 1 osobu', count: 1 },
          ],
          amenities: [
            'Balkon',
            'Klima uređaj',
            'Besplatni WiFi',
            'TV s ravnim ekranom',
            'Privatna kupaonica',
            'Hladnjak',
            'Radni stol',
            'Drveni pod',
            'Grijanje',
          ],
          amenitiesEn: [
            'Balcony',
            'Air conditioning',
            'Free WiFi',
            'Flat-screen TV',
            'Private bathroom',
            'Fridge',
            'Desk',
            'Hardwood floor',
            'Heating',
          ],
          heroImage: '/images/rooms/563273867.jpg',

          gallery: [
            'https://images.unsplash.com/photo-1618773928121-c32242e63f39?q=85&w=1200&auto=format&fit=crop',
            'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?q=85&w=1200&auto=format&fit=crop',
          ],
        },
        {
          id: 'trokrevetna-economy',
          name: 'Trokrevetna soba Economy',
          nameEn: 'Economy Triple Room',
          descriptionHr:
            'Soba od 28 m² s prostorom za sjedenje, TV ravnog ekrana i radnim stolom. Bez balkona.',
          descriptionEn: '28 m² room with seating area, flat-screen TV and desk. No balcony.',
          guests: 3,
          sizeM2: 28,
          hasBalcony: false,
          beds: [
            { type: 'Veliki bračni krevet', count: 1 },
            { type: 'Krevet za 1 osobu', count: 1 },
          ],
          amenities: [
            'Klima uređaj',
            'Besplatni WiFi',
            'TV s ravnim ekranom',
            'Privatna kupaonica',
            'Hladnjak',
            'Radni stol',
            'Drveni pod',
            'Grijanje',
          ],
          amenitiesEn: [
            'Air conditioning',
            'Free WiFi',
            'Flat-screen TV',
            'Private bathroom',
            'Fridge',
            'Desk',
            'Hardwood floor',
            'Heating',
          ],
          heroImage: '/images/rooms/563273867.jpg',

          gallery: [
            'https://images.unsplash.com/photo-1566665797739-1674de7a421a?q=85&w=1200&auto=format&fit=crop',
          ],
        },
        {
          id: 'cetverokretna',
          name: 'Četverokrevetna soba',
          nameEn: 'Quadruple Room',
          descriptionHr:
            'Prostrana soba od 38 m² s balkonom, prostorom za sjedenje, TV ravnog ekrana i zasebnim klima uređajem.',
          descriptionEn:
            'Spacious 38 m² room with balcony, seating area, flat-screen TV and separate air conditioning.',
          guests: 4,
          sizeM2: 38,
          hasBalcony: true,
          beds: [
            { type: 'Veliki bračni krevet', count: 1 },
            { type: 'Krevet za 1 osobu', count: 2 },
          ],
          amenities: [
            'Balkon',
            'Zasebni klima uređaj',
            'Besplatni WiFi',
            'TV s ravnim ekranom',
            'Privatna kupaonica',
            'Hladnjak',
            'Radni stol',
            'Drveni pod',
            'Grijanje',
          ],
          amenitiesEn: [
            'Balcony',
            'Separate air conditioning',
            'Free WiFi',
            'Flat-screen TV',
            'Private bathroom',
            'Fridge',
            'Desk',
            'Hardwood floor',
            'Heating',
          ],
          heroImage: '/images/rooms/563273867.jpg',

          gallery: [
            'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?q=85&w=1200&auto=format&fit=crop',
            'https://images.unsplash.com/photo-1618773928121-c32242e63f39?q=85&w=1200&auto=format&fit=crop',
          ],
        },
        {
          id: 'dvokrevetna-standard',
          name: 'Dvokrevetna soba s bračnim krevetom',
          nameEn: 'Standard Double Room',
          descriptionHr:
            'Standardna soba od 22 m² s prostorom za sjedenje, TV ravnog ekrana i privatnom kupaonicom. Bez balkona.',
          descriptionEn:
            'Standard 22 m² room with seating area, flat-screen TV and private bathroom. No balcony.',
          guests: 2,
          sizeM2: 22,
          hasBalcony: false,
          beds: [{ type: 'Veliki bračni krevet', count: 1 }],
          amenities: [
            'Klima uređaj',
            'Besplatni WiFi',
            'TV s ravnim ekranom',
            'Privatna kupaonica',
            'Hladnjak',
            'Radni stol',
            'Drveni pod',
            'Grijanje',
          ],
          amenitiesEn: [
            'Air conditioning',
            'Free WiFi',
            'Flat-screen TV',
            'Private bathroom',
            'Fridge',
            'Desk',
            'Hardwood floor',
            'Heating',
          ],
          heroImage: '/images/rooms/563273867.jpg',

          gallery: [
            'https://images.unsplash.com/photo-1505693314120-0d443867891c?q=85&w=1200&auto=format&fit=crop',
          ],
        },
      ],
    },

    // ──────────────────────────────────────────────────────
    // AVALENA PENTHOUSE — s pravim slikama
    // ──────────────────────────────────────────────────────
    {
      id: 'penthouse',
      name: 'Avalena Penthouse',
      taglineHr: '200 m² · 5 spavaćih soba · Panoramska terasa',
      taglineEn: '200 m² · 5 bedrooms · Panoramic terrace',
      descriptionHr:
        'Luksuzni apartman na vrhu zgrade s pet spavaćih soba, pet kupaonica i prostranom terasom s pogledom na grad.',
      descriptionEn:
        'Luxury top-floor apartment with five bedrooms, five bathrooms and a spacious terrace overlooking the city.',
      longDescriptionHr:
        'Avalena Penthouse je prostrani luksuzni apartman od 200 m² smješten na vrhu zgrade s pogledom na grad i panoramskom terasom. Apartman raspolaže s pet spavaćih soba, pet kupaonica, velikom dnevnom sobom s 49" Smart TV-om, potpuno opremljenom kuhinjom (perilica suđa, ploča za kuhanje, mikrovalna), te pralionom rublja. Svi kreveti su dugi > 2 metra. Netflix i streaming servisi dostupni. Gornji katovi — isključivo stepenicama.',
      longDescriptionEn:
        'Avalena Penthouse is a 200 m² luxury apartment on the top floor with city views and a panoramic terrace. The apartment features five bedrooms, five bathrooms, a large living room with a 49" Smart TV, a fully equipped kitchen (dishwasher, hob, microwave) and a washing machine. All beds exceed 2 metres. Netflix and streaming services available. Upper floors — stairs only.',
      addressHr: 'Ul. Augusta Šenoe 22, Borik, Zadar',
      addressEn: 'Ul. Augusta Šenoe 22, Borik, Zadar',
      heroImage: '/images/penthouse/terasa.jpg',
      gallery: [
        '/images/penthouse/terasa.jpg',
        '/images/penthouse/dnevni-boravak.jpg',
        '/images/penthouse/soba1-bracni.jpg',
        '/images/penthouse/soba5-zlatna.jpg',
      ],
      rooms: [
        {
          id: 'penthouse-cijeli',
          name: 'Penthouse apartman — cijeli (200 m²)',
          nameEn: 'Penthouse Apartment — Entire (200 m²)',
          descriptionHr:
            'Cijeli penthouse apartman od 200 m² s pet spavaćih soba, pet kupaonica, dnevnim boravkom, potpuno opremljenom kuhinjom i panoramskom terasom s pogledom na grad.',
          descriptionEn:
            'The entire 200 m² penthouse with five bedrooms, five bathrooms, living room, fully equipped kitchen and panoramic city-view terrace.',
          guests: 10,
          sizeM2: 200,
          hasBalcony: true,
          beds: [
            { type: 'Veliki bračni krevet', count: 4 },
            { type: 'Krevet za 1 osobu', count: 1 },
            { type: 'Sofa-krevet u dnevnom boravku', count: 1 },
          ],
          amenities: [
            'Panoramska terasa',
            'Pogled na grad',
            '5 spavaćih soba',
            '5 kupaonica',
            'Perilica suđa',
            'Perilica rublja',
            'Potpuno opremljena kuhinja',
            'Klima uređaj',
            'Besplatni WiFi',
            'Parking',
            'Netflix/Streaming',
            'Kreveti > 2 m',
          ],
          amenitiesEn: [
            'Panoramic terrace',
            'City view',
            '5 bedrooms',
            '5 bathrooms',
            'Dishwasher',
            'Washing machine',
            'Fully equipped kitchen',
            'Air conditioning',
            'Free WiFi',
            'Parking',
            'Netflix/Streaming',
            'Beds > 2 m',
          ],
          heroImage: '/images/penthouse/terasa.jpg',
          gallery: [
            '/images/penthouse/terasa.jpg',
            '/images/penthouse/dnevni-boravak.jpg',
            '/images/penthouse/soba1-bracni.jpg',
            '/images/penthouse/soba2-bracni.jpg',
            '/images/penthouse/soba3-prozor.jpg',
            '/images/penthouse/soba4-bracni.jpg',
            '/images/penthouse/soba5-zlatna.jpg',
          ],
        },
      ],
    },

    // ──────────────────────────────────────────────────────
    // AVALENA RESIDENCE
    // ──────────────────────────────────────────────────────
    {
      id: 'residence',
      name: 'Avalena Residence',
      taglineHr: 'Apartmani za obitelji i dulje boravke',
      taglineEn: 'Apartments for families and longer stays',
      descriptionHr:
        'Prostrani apartmani s odvojenim dnevnim prostorom, potpuno opremljenom kuhinjom i privatnom terasom — idealno za obitelji.',
      descriptionEn:
        'Spacious apartments with separate living area, fully equipped kitchen and private terrace — ideal for families.',
      longDescriptionHr:
        'Avalena Residence nudi apartmane prilagođene obiteljima i gostima koji planiraju dulje boravke u Boriku. Svaki apartman ima odvojenu dnevnu sobu, potpuno opremljenu kuhinju i privatnu terasu ili balkon. Klima uređaj, besplatni WiFi i parking uključeni. 400 m od mora.',
      longDescriptionEn:
        'Avalena Residence offers apartments suited to families and guests planning longer stays in Borik. Each apartment has a separate living room, fully equipped kitchen and private terrace or balcony. Air conditioning, free WiFi and parking included. 400 m from the sea.',
      addressHr: 'Borik, Zadar',
      addressEn: 'Borik, Zadar',
      heroImage: '/images/residence/bazen.jpg',
      gallery: [
        '/images/residence/582404466.jpg',
        '/images/residence/883201012.jpg',
        '/images/residence/dvor.jpg',
        '/images/residence/bazen2.jpg',
      ],
      rooms: [
        {
          id: 'dvokrevetna-balkon',
          name: 'Dvokrevetna soba s balkonom',
          nameEn: 'Double Room with Balcony',
          descriptionHr:
            'Klimatizirana soba od 23 m² s velikim bračnim krevetom i namještenim balkonom s pogledom na vrt. Opremljena je TV-om sa satelitskim programima, hladnjakom, električnim kuhalom i privatnom kupaonicom.',
          descriptionEn:
            'Air-conditioned 23 m² room with a large double bed and a furnished balcony overlooking the garden. Includes satellite TV, a fridge, an electric kettle and a private bathroom.',
          guests: 2,
          sizeM2: 23,
          hasBalcony: true,
          beds: [{ type: 'Veliki bračni krevet', count: 1 }],
          amenities: [
            'Balkon',
            'Pogled na vrt',
            'Klima uređaj',
            'Besplatni WiFi',
            'TV s ravnim ekranom',
            'Satelitski programi',
            'Privatna kupaonica',
            'Hladnjak',
            'Električno kuhalo',
            'Prostor za sjedenje',
            'Radni stol',
            'Ogrtač',
            'Papuče',
            'Fen',
            'Grijanje',
          ],
          amenitiesEn: [
            'Balcony',
            'Garden view',
            'Air conditioning',
            'Free WiFi',
            'Flat-screen TV',
            'Satellite channels',
            'Private bathroom',
            'Fridge',
            'Electric kettle',
            'Seating area',
            'Desk',
            'Bathrobe',
            'Slippers',
            'Hairdryer',
            'Heating',
          ],
          heroImage: '/images/residence/582404466.jpg',
          gallery: ['/images/residence/582404466.jpg', '/images/residence/883201012.jpg'],
        },
        {
          id: 'cetverokrevetna',
          name: 'Četverokrevetna soba',
          nameEn: 'Quadruple Room',
          descriptionHr:
            'Smještaj od 31 m² sastoji se od dvije povezane sobe koje dijele balkon. Sadrži veliki bračni krevet, krevet na kat, satelitski TV, hladnjak, električno kuhalo i privatnu kupaonicu.',
          descriptionEn:
            'This 31 m² accommodation consists of two interconnected rooms sharing a balcony. It includes a large double bed, bunk bed, satellite TV, fridge, electric kettle and private bathroom.',
          guests: 4,
          sizeM2: 31,
          hasBalcony: true,
          beds: [
            { type: 'Veliki bračni krevet', count: 1 },
            { type: 'Krevet na kat', count: 1 },
          ],
          amenities: [
            'Balkon',
            'Dvije povezane sobe',
            'Klima uređaj',
            'Besplatni WiFi',
            'TV s ravnim ekranom',
            'Satelitski programi',
            'Privatna kupaonica',
            'Hladnjak',
            'Električno kuhalo',
            'Prostor za sjedenje',
            'Radni stol',
            'Vanjski namještaj',
            'Ogrtač',
            'Papuče',
            'Fen',
            'Grijanje',
          ],
          amenitiesEn: [
            'Balcony',
            'Two interconnected rooms',
            'Air conditioning',
            'Free WiFi',
            'Flat-screen TV',
            'Satellite channels',
            'Private bathroom',
            'Fridge',
            'Electric kettle',
            'Seating area',
            'Desk',
            'Outdoor furniture',
            'Bathrobe',
            'Slippers',
            'Hairdryer',
            'Heating',
          ],
          heroImage: '/images/residence/883201012.jpg',
          gallery: ['/images/residence/883201012.jpg', '/images/residence/582404466.jpg'],
        },
        {
          id: 'dvokrevetna',
          name: 'Dvokrevetna soba',
          nameEn: 'Double Room',
          descriptionHr:
            'Klimatizirana soba od 20 m² s velikim bračnim krevetom i pogledom na vrt. Sadrži TV ravnog ekrana sa satelitskim programima, hladnjak, električno kuhalo i privatnu kupaonicu s tušem.',
          descriptionEn:
            'Air-conditioned 20 m² room with a large double bed and garden view. Includes a flat-screen satellite TV, fridge, electric kettle and private bathroom with shower.',
          guests: 2,
          sizeM2: 20,
          hasBalcony: false,
          beds: [{ type: 'Veliki bračni krevet', count: 1 }],
          amenities: [
            'Pogled na vrt',
            'Klima uređaj',
            'Besplatni WiFi',
            'TV s ravnim ekranom',
            'Satelitski programi',
            'Privatna kupaonica',
            'Hladnjak',
            'Električno kuhalo',
            'Mreža protiv komaraca',
            'Prostor za sjedenje',
            'Radni stol',
            'Ogrtač',
            'Papuče',
            'Fen',
            'Grijanje',
          ],
          amenitiesEn: [
            'Garden view',
            'Air conditioning',
            'Free WiFi',
            'Flat-screen TV',
            'Satellite channels',
            'Private bathroom',
            'Fridge',
            'Electric kettle',
            'Mosquito net',
            'Seating area',
            'Desk',
            'Bathrobe',
            'Slippers',
            'Hairdryer',
            'Heating',
          ],
          heroImage: '/images/residence/dvor.jpg',
          gallery: ['/images/residence/dvor.jpg', '/images/residence/582404466.jpg'],
        },
        {
          id: 'twin-balkon',
          name: 'Soba s 2 odvojena kreveta i balkonom',
          nameEn: 'Twin Room with Balcony',
          descriptionHr:
            'Klimatizirana soba od 16 m² s dva odvojena kreveta, privatnim balkonom, TV-om sa satelitskim programima i privatnom kupaonicom.',
          descriptionEn:
            'Air-conditioned 16 m² room with two single beds, a private balcony, satellite TV and a private bathroom.',
          guests: 2,
          sizeM2: 16,
          hasBalcony: true,
          beds: [{ type: 'Krevet za 1 osobu', count: 2 }],
          amenities: [
            'Balkon',
            'Klima uređaj',
            'Besplatni WiFi',
            'TV s ravnim ekranom',
            'Satelitski programi',
            'Privatna kupaonica',
            'Hladnjak',
            'Električno kuhalo',
            'Prostor za sjedenje',
            'Radni stol',
            'Vanjski namještaj',
            'Ogrtač',
            'Papuče',
            'Fen',
            'Grijanje',
          ],
          amenitiesEn: [
            'Balcony',
            'Air conditioning',
            'Free WiFi',
            'Flat-screen TV',
            'Satellite channels',
            'Private bathroom',
            'Fridge',
            'Electric kettle',
            'Seating area',
            'Desk',
            'Outdoor furniture',
            'Bathrobe',
            'Slippers',
            'Hairdryer',
            'Heating',
          ],
          heroImage: '/images/residence/bazen2.jpg',
          gallery: ['/images/residence/bazen2.jpg', '/images/residence/883201012.jpg'],
        },
        {
          id: 'king-balkon',
          name: 'King soba s balkonom',
          nameEn: 'King Room with Balcony',
          descriptionHr:
            'Klimatizirana soba od 20 m² s velikim bračnim krevetom, privatnim balkonom, TV-om sa satelitskim programima i privatnom kupaonicom.',
          descriptionEn:
            'Air-conditioned 20 m² room with a large double bed, private balcony, satellite TV and a private bathroom.',
          guests: 2,
          sizeM2: 20,
          hasBalcony: true,
          beds: [{ type: 'Veliki bračni krevet', count: 1 }],
          amenities: [
            'Balkon',
            'Klima uređaj',
            'Besplatni WiFi',
            'TV s ravnim ekranom',
            'Satelitski programi',
            'Privatna kupaonica',
            'Hladnjak',
            'Električno kuhalo',
            'Prostor za sjedenje',
            'Radni stol',
            'Vanjski namještaj',
            'Ogrtač',
            'Papuče',
            'Fen',
            'Grijanje',
          ],
          amenitiesEn: [
            'Balcony',
            'Air conditioning',
            'Free WiFi',
            'Flat-screen TV',
            'Satellite channels',
            'Private bathroom',
            'Fridge',
            'Electric kettle',
            'Seating area',
            'Desk',
            'Outdoor furniture',
            'Bathrobe',
            'Slippers',
            'Hairdryer',
            'Heating',
          ],
          heroImage: '/images/residence/582404466.jpg',
          gallery: ['/images/residence/582404466.jpg', '/images/residence/bazen2.jpg'],
        },
        {
          id: 'trokrevetna-terasa',
          name: 'Trokrevetna soba s terasom',
          nameEn: 'Triple Room with Terrace',
          descriptionHr:
            'Klimatizirana soba od 28 m² s velikim bračnim krevetom, kaučem na rasklapanje i privatnom terasom. Opremljena je satelitskim TV-om, hladnjakom i privatnom kupaonicom.',
          descriptionEn:
            'Air-conditioned 28 m² room with a large double bed, sofa bed and private terrace. Includes satellite TV, fridge and a private bathroom.',
          guests: 3,
          sizeM2: 28,
          hasBalcony: true,
          beds: [
            { type: 'Veliki bračni krevet', count: 1 },
            { type: 'Sofa-krevet', count: 1 },
          ],
          amenities: [
            'Terasa',
            'Balkon',
            'Klima uređaj',
            'Besplatni WiFi',
            'TV s ravnim ekranom',
            'Satelitski programi',
            'Privatna kupaonica',
            'Hladnjak',
            'Električno kuhalo',
            'Mreža protiv komaraca',
            'Prostor za sjedenje',
            'Vanjski namještaj',
            'Sofa-krevet',
            'Ogrtač',
            'Papuče',
            'Fen',
          ],
          amenitiesEn: [
            'Terrace',
            'Balcony',
            'Air conditioning',
            'Free WiFi',
            'Flat-screen TV',
            'Satellite channels',
            'Private bathroom',
            'Fridge',
            'Electric kettle',
            'Mosquito net',
            'Seating area',
            'Outdoor furniture',
            'Sofa bed',
            'Bathrobe',
            'Slippers',
            'Hairdryer',
          ],
          heroImage: '/images/residence/dvor.jpg',
          gallery: ['/images/residence/dvor.jpg', '/images/residence/bazen2.jpg'],
        },
        {
          id: 'deluxe-trokrevetna',
          name: 'Deluxe trokrevetna soba',
          nameEn: 'Deluxe Triple Room',
          descriptionHr:
            'Vrlo prostrana soba od 70 m² s velikim bračnim krevetom, kaučem na rasklapanje, prostorom za sjedenje i privatnom terasom. Sadrži TV ravnog ekrana, radni stol i privatnu kupaonicu.',
          descriptionEn:
            'Very spacious 70 m² room with a large double bed, sofa bed, seating area and private terrace. Includes a flat-screen TV, desk and private bathroom.',
          guests: 3,
          sizeM2: 70,
          hasBalcony: true,
          beds: [
            { type: 'Veliki bračni krevet', count: 1 },
            { type: 'Sofa-krevet', count: 1 },
          ],
          amenities: [
            'Terasa',
            'Balkon',
            'Klima uređaj',
            'Besplatni WiFi',
            'Sofa',
            'TV s ravnim ekranom',
            'Satelitski programi',
            'Privatna kupaonica',
            'Hladnjak',
            'Električno kuhalo',
            'Mreža protiv komaraca',
            'Prostor za sjedenje',
            'Radni stol',
            'Vanjski namještaj',
            'Sofa-krevet',
            'Ogrtač',
            'Papuče',
            'Fen',
          ],
          amenitiesEn: [
            'Terrace',
            'Balcony',
            'Air conditioning',
            'Free WiFi',
            'Sofa',
            'Flat-screen TV',
            'Satellite channels',
            'Private bathroom',
            'Fridge',
            'Electric kettle',
            'Mosquito net',
            'Seating area',
            'Desk',
            'Outdoor furniture',
            'Sofa bed',
            'Bathrobe',
            'Slippers',
            'Hairdryer',
          ],
          heroImage: '/images/residence/883201012.jpg',
          gallery: [
            '/images/residence/883201012.jpg',
            '/images/residence/dvor.jpg',
            '/images/residence/bazen2.jpg',
          ],
        },
        {
          id: 'standard-cetverokrevetna',
          name: 'Standardna četverokrevetna soba',
          nameEn: 'Standard Quadruple Room',
          descriptionHr:
            'Klimatizirana soba od 28 m² s velikim bračnim krevetom, kaučem na rasklapanje i privatnim balkonom. Opremljena je satelitskim TV-om, hladnjakom, električnim kuhalom i privatnom kupaonicom.',
          descriptionEn:
            'Air-conditioned 28 m² room with a large double bed, sofa bed and private balcony. Includes satellite TV, fridge, electric kettle and a private bathroom.',
          guests: 4,
          sizeM2: 28,
          hasBalcony: true,
          beds: [
            { type: 'Veliki bračni krevet', count: 1 },
            { type: 'Sofa-krevet', count: 1 },
          ],
          amenities: [
            'Balkon',
            'Klima uređaj',
            'Besplatni WiFi',
            'TV s ravnim ekranom',
            'Satelitski programi',
            'Privatna kupaonica',
            'Hladnjak',
            'Električno kuhalo',
            'Prostor za sjedenje',
            'Radni stol',
            'Sofa-krevet',
            'Ogrtač',
            'Papuče',
            'Fen',
            'Grijanje',
          ],
          amenitiesEn: [
            'Balcony',
            'Air conditioning',
            'Free WiFi',
            'Flat-screen TV',
            'Satellite channels',
            'Private bathroom',
            'Fridge',
            'Electric kettle',
            'Seating area',
            'Desk',
            'Sofa bed',
            'Bathrobe',
            'Slippers',
            'Hairdryer',
            'Heating',
          ],
          heroImage: '/images/residence/582404466.jpg',
          gallery: ['/images/residence/582404466.jpg', '/images/residence/883201012.jpg'],
        },
        {
          id: 'trokrevetna-balkon',
          name: 'Trokrevetna soba s balkonom',
          nameEn: 'Triple Room with Balcony',
          descriptionHr:
            'Klimatizirana soba od 25 m² s velikim bračnim krevetom, kaučem na rasklapanje i privatnim balkonom. Sadrži TV sa satelitskim programima, hladnjak, električno kuhalo i privatnu kupaonicu.',
          descriptionEn:
            'Air-conditioned 25 m² room with a large double bed, sofa bed and private balcony. Includes satellite TV, fridge, electric kettle and a private bathroom.',
          guests: 3,
          sizeM2: 25,
          hasBalcony: true,
          beds: [
            { type: 'Veliki bračni krevet', count: 1 },
            { type: 'Sofa-krevet', count: 1 },
          ],
          amenities: [
            'Balkon',
            'Klima uređaj',
            'Besplatni WiFi',
            'TV s ravnim ekranom',
            'Satelitski programi',
            'Privatna kupaonica',
            'Hladnjak',
            'Električno kuhalo',
            'Radni stol',
            'Vanjski namještaj',
            'Sofa-krevet',
            'Ogrtač',
            'Papuče',
            'Fen',
            'Grijanje',
          ],
          amenitiesEn: [
            'Balcony',
            'Air conditioning',
            'Free WiFi',
            'Flat-screen TV',
            'Satellite channels',
            'Private bathroom',
            'Fridge',
            'Electric kettle',
            'Desk',
            'Outdoor furniture',
            'Sofa bed',
            'Bathrobe',
            'Slippers',
            'Hairdryer',
            'Heating',
          ],
          heroImage: '/images/residence/bazen2.jpg',
          gallery: ['/images/residence/bazen2.jpg', '/images/residence/dvor.jpg'],
        },
      ],
    },

    // ──────────────────────────────────────────────────────
    // AVALENA VILA INES
    // ──────────────────────────────────────────────────────
    {
      id: 'vila-ines',
      name: 'Avalena Art Villa Ines',
      taglineHr: 'Bazen · Galerija · 400 m od mora',
      taglineEn: 'Pool · Art gallery · 400 m from the sea',
      descriptionHr:
        'Guesthouse s obiteljskim sobama, sezonskim bazenom od 80 m², mediteranskim vrtom i galerijom umjetnina — 400 m od plaže.',
      descriptionEn:
        'Guest house with family rooms, 80 m² seasonal pool, Mediterranean garden and art gallery — 400 m from the beach.',
      longDescriptionHr:
        'Avalena Vila Ines smještena je u mirnom dijelu Borika, 400 m od šljunčane plaže. Vila raspolaže sezonskim vanjskim bazenom (80 m²), prostranim mediteranskim vrtom s terasama i gazebima, te galerijom umjetnina vlasnice dr. Ines Jurin. Sobe su klimatizirane, ukrašene originalnim slikama, s pogledom na more ili vrt. Privatna kupaonica s tušem, fenom i ogrtačima. Besplatno parkiralište za sve goste.',
      longDescriptionEn:
        'Avalena Vila Ines is set in a quiet part of Borik, 400 m from a pebbly beach. The villa features an 80 m² seasonal outdoor pool, a large Mediterranean garden with terraces and gazebos, and the art gallery of owner Dr. Ines Jurin. Rooms are air-conditioned, decorated with original paintings, with sea or garden views. Private bathroom with shower, hairdryer and robes. Free parking for all guests.',
      addressHr: 'Borik, Zadar',
      addressEn: 'Borik, Zadar',
      heroImage: '/images/vila-ines/883427780.jpg',
      gallery: [
        '/images/vila-ines/528894444.jpg',
        '/images/vila-ines/582271891.jpg',
        '/images/vila-ines/582272087.jpg',
        '/images/vila-ines/883427780.jpg',
      ],
      rooms: [
        {
          id: 'dvokrevetna-balkon',
          name: 'Dvokrevetna soba s bračnim krevetom i balkonom',
          nameEn: 'Double Room with Double Bed and Balcony',
          descriptionHr:
            'Klimatizirana soba od 20 m² s namještenim balkonom i pogledom na more, bazen i grad. Sadrži prostor za sjedenje, satelitski TV ravnog ekrana, hladnjak i električno kuhalo. Privatna kupaonica opremljena je kadom, tušem, fenom, ogrtačem, papučama i besplatnim toaletnim priborom.',
          descriptionEn:
            'Featuring a furnished balcony with a sea view, this air-conditioned room offers a seating area with a flat-screen satellite TV, a fridge and an electric kettle. The bathroom is equipped with a bathtub, a shower and provides a hairdryer, a bathrobe and free toiletries.',
          guests: 2,
          sizeM2: 20,
          hasBalcony: true,
          beds: [{ type: 'Veliki bračni krevet', count: 1 }],
          amenities: [
            'Balkon',
            'Pogled na more',
            'Pogled na bazen',
            'Pogled na grad',
            'Kada i tuš',
            'Privatna kupaonica',
            'Besplatni toaletni pribor',
            'Ogrtač i papuče',
            'Fen',
            'Klima uređaj',
            'Zaseban klima uređaj',
            'Besplatni WiFi',
            'TV s ravnim ekranom',
            'Satelitski programi',
            'Hladnjak',
            'Električno kuhalo',
            'Aparat za kavu/čaj',
            'Prostor za sjedenje',
            'Radni stol',
            'Drveni ili parketni pod',
            'Mreža protiv komaraca',
            'Vanjski namještaj',
            'Popločano dvorište',
            'Grijanje',
            'Gornji katovi dostupni stepenicama',
            'Zabranjeno pušenje',
          ],
          amenitiesEn: [
            'Balcony',
            'Sea view',
            'Pool view',
            'City view',
            'Bathtub and shower',
            'Private bathroom',
            'Free toiletries',
            'Bathrobe and slippers',
            'Hairdryer',
            'Air conditioning',
            'Individual air conditioning',
            'Free WiFi',
            'Flat-screen TV',
            'Satellite channels',
            'Fridge',
            'Electric kettle',
            'Tea/coffee maker',
            'Seating area',
            'Desk',
            'Hardwood or parquet floor',
            'Mosquito net',
            'Outdoor furniture',
            'Patio',
            'Heating',
            'Upper floors accessible by stairs only',
            'No smoking',
          ],
          heroImage: '/images/vila-ines/528894444.jpg',
          gallery: [
            '/images/vila-ines/528894444.jpg',
            '/images/vila-ines/582271891.jpg',
            '/images/vila-ines/582272087.jpg',
            '/images/vila-ines/883427780.jpg',
          ],
        },
        {
          id: 'dvokrevetna',
          name: 'Dvokrevetna soba s bračnim krevetom',
          nameEn: 'Double Room with Double Bed',
          descriptionHr:
            'Klimatizirana soba od 18 m² s pogledom na more, vrt i grad. Opremljena je prostorom za sjedenje, satelitskim TV-om ravnog ekrana, hladnjakom i električnim kuhalom. Privatna kupaonica ima kadu ili tuš, fen, ogrtač, papuče i besplatni toaletni pribor.',
          descriptionEn:
            'Overlooking the sea, this air-conditioned room comes with a seating area and a flat-screen satellite TV, as well as a fridge and an electric kettle. The bathroom is fitted with a shower and provides a hairdryer and a bathrobe.',
          guests: 2,
          sizeM2: 18,
          hasBalcony: false,
          beds: [{ type: 'Veliki bračni krevet', count: 1 }],
          amenities: [
            'Pogled na more',
            'Pogled na vrt',
            'Pogled na grad',
            'Privatna kupaonica',
            'Kada ili tuš',
            'Besplatni toaletni pribor',
            'Ogrtač i papuče',
            'Fen',
            'Klima uređaj',
            'Zaseban klima uređaj',
            'Besplatni WiFi',
            'TV s ravnim ekranom',
            'Satelitski programi',
            'Hladnjak',
            'Električno kuhalo',
            'Aparat za kavu/čaj',
            'Prostor za sjedenje',
            'Radni stol',
            'Drveni ili parketni pod',
            'Mreža protiv komaraca',
            'Popločano dvorište',
            'Grijanje',
            'Gornji katovi dostupni stepenicama',
            'Zabranjeno pušenje',
          ],
          amenitiesEn: [
            'Sea view',
            'Garden view',
            'City view',
            'Private bathroom',
            'Bath or shower',
            'Free toiletries',
            'Bathrobe and slippers',
            'Hairdryer',
            'Air conditioning',
            'Individual air conditioning',
            'Free WiFi',
            'Flat-screen TV',
            'Satellite channels',
            'Fridge',
            'Electric kettle',
            'Tea/coffee maker',
            'Seating area',
            'Desk',
            'Hardwood or parquet floor',
            'Mosquito net',
            'Patio',
            'Heating',
            'Upper floors accessible by stairs only',
            'No smoking',
          ],
          heroImage: '/images/vila-ines/582271891.jpg',
          gallery: [
            '/images/vila-ines/582271891.jpg',
            '/images/vila-ines/528894444.jpg',
            '/images/vila-ines/582272087.jpg',
          ],
        },
        {
          id: 'cetverokrevetna',
          name: 'Četverokrevetna soba',
          nameEn: 'Quadruple Room',
          descriptionHr:
            'Klimatizirana soba od 28 m² s dva velika bračna kreveta, pogledom na vrt i bazen te zasebnim ulazom koji omogućuje jednostavan pristup bazenu i maloj namještenoj terasi. Opremljena je prostorom za sjedenje, satelitskim TV-om, hladnjakom i električnim kuhalom.',
          descriptionEn:
            'This air-conditioned room features a seating area and a flat-screen satellite TV, as well as a fridge and an electric kettle. The bathroom is fitted with a shower and provides a hairdryer and a bathrobe. This room has an additional entrance that provides easy access to the swimming pool and a small furnished patio.',
          guests: 4,
          sizeM2: 28,
          hasBalcony: false,
          beds: [{ type: 'Veliki bračni krevet', count: 2 }],
          amenities: [
            'Pogled na vrt',
            'Pogled na bazen',
            'Zaseban ulaz',
            'Izravan pristup bazenu',
            'Popločano dvorište',
            'Privatna kupaonica',
            'Kada ili tuš',
            'Besplatni toaletni pribor',
            'Ogrtač i papuče',
            'Fen',
            'Klima uređaj',
            'Zaseban klima uređaj',
            'Besplatni WiFi',
            'TV s ravnim ekranom',
            'Satelitski programi',
            'Hladnjak',
            'Električno kuhalo',
            'Aparat za kavu/čaj',
            'Prostor za sjedenje',
            'Radni stol',
            'Drveni ili parketni pod',
            'Mreža protiv komaraca',
            'Povezane sobe',
            'Jedinica u prizemlju',
            'Kauč na rasklapanje',
            'Grijanje',
            'Zabranjeno pušenje',
          ],
          amenitiesEn: [
            'Garden view',
            'Pool view',
            'Private entrance',
            'Direct pool access',
            'Patio',
            'Private bathroom',
            'Bath or shower',
            'Free toiletries',
            'Bathrobe and slippers',
            'Hairdryer',
            'Air conditioning',
            'Individual air conditioning',
            'Free WiFi',
            'Flat-screen TV',
            'Satellite channels',
            'Fridge',
            'Electric kettle',
            'Tea/coffee maker',
            'Seating area',
            'Desk',
            'Hardwood or parquet floor',
            'Mosquito net',
            'Interconnected rooms available',
            'Entire unit on ground floor',
            'Sofa bed',
            'Heating',
            'No smoking',
          ],
          heroImage: '/images/vila-ines/582272087.jpg',
          gallery: [
            '/images/vila-ines/582272087.jpg',
            '/images/vila-ines/883427780.jpg',
            '/images/vila-ines/528894444.jpg',
          ],
        },
        {
          id: 'apartman-1-spavaca',
          name: 'Apartman s 1 spavaćom sobom',
          nameEn: 'One-Bedroom Apartment',
          descriptionHr:
            'Klimatizirani apartman od 34 m² s jednom spavaćom sobom, dnevnim boravkom, velikim bračnim krevetom i kaučem na rasklapanje. Ima pogled na vrt, vlastitu čajnu kuhinju sa stolom za blagovanje te privatnu kupaonicu.',
          descriptionEn:
            'This air-conditioned apartment comes with a living room comprising a seating area and a flat-screen satellite TV. The equipped kitchenette comes with a dining table, while the bathroom is fitted with a shower and includes a hairdryer and a bathrobe.',
          guests: 4,
          sizeM2: 34,
          hasBalcony: false,
          beds: [
            { type: 'Veliki bračni krevet', count: 1 },
            { type: 'Kauč na rasklapanje', count: 1 },
          ],
          amenities: [
            'Pogled na vrt',
            'Čajna kuhinja',
            'Ploča za kuhanje',
            'Kuhinjski pribor',
            'Hladnjak',
            'Električno kuhalo',
            'Stol za blagovanje',
            'Privatna kupaonica',
            'Kada ili tuš',
            'Besplatni toaletni pribor',
            'Ogrtač i papuče',
            'Fen',
            'Klima uređaj',
            'Zaseban klima uređaj',
            'Besplatni WiFi',
            'TV s ravnim ekranom',
            'Satelitski programi',
            'Dnevni boravak',
            'Prostor za sjedenje',
            'Kauč na rasklapanje',
            'Radni stol',
            'Drveni ili parketni pod',
            'Mreža protiv komaraca',
            'Povezane sobe',
            'Popločano dvorište',
            'Jedinica u prizemlju',
            'Grijanje',
            'Zabranjeno pušenje',
          ],
          amenitiesEn: [
            'Garden view',
            'Kitchenette',
            'Stovetop',
            'Kitchenware',
            'Fridge',
            'Electric kettle',
            'Dining table',
            'Private bathroom',
            'Bath or shower',
            'Free toiletries',
            'Bathrobe and slippers',
            'Hairdryer',
            'Air conditioning',
            'Individual air conditioning',
            'Free WiFi',
            'Flat-screen TV',
            'Satellite channels',
            'Living room',
            'Seating area',
            'Sofa bed',
            'Desk',
            'Hardwood or parquet floor',
            'Mosquito net',
            'Interconnected rooms available',
            'Patio',
            'Entire unit on ground floor',
            'Heating',
            'No smoking',
          ],
          heroImage: '/images/vila-ines/883427780.jpg',
          gallery: [
            '/images/vila-ines/883427780.jpg',
            '/images/vila-ines/582272087.jpg',
            '/images/vila-ines/582271891.jpg',
            '/images/vila-ines/528894444.jpg',
          ],
        },
        {
          id: 'suite-1-spavaca',
          name: 'Suite s 1 spavaćom sobom',
          nameEn: 'One-Bedroom Suite',
          descriptionHr:
            'Klimatizirani suite od 45 m² s jednom spavaćom sobom, dnevnim boravkom, velikim bračnim krevetom i kaučem na rasklapanje. Ima namješteni balkon s pogledom na more, vrt i grad, vlastitu čajnu kuhinju, blagovaonicu i privatnu kupaonicu.',
          descriptionEn:
            'Air-conditioned suite featuring a furnished balcony, a living room and a flat-screen satellite TV, as well as a fridge and an electric kettle. The bathroom is fitted with a shower and provides a hairdryer and a bathrobe.',
          guests: 4,
          sizeM2: 45,
          hasBalcony: true,
          beds: [
            { type: 'Veliki bračni krevet', count: 1 },
            { type: 'Kauč na rasklapanje', count: 1 },
          ],
          amenities: [
            'Balkon',
            'Pogled na more',
            'Pogled na vrt',
            'Pogled na grad',
            'Čajna kuhinja',
            'Ploča za kuhanje',
            'Kuhinjski pribor',
            'Hladnjak',
            'Električno kuhalo',
            'Blagovaonica',
            'Stol za blagovanje',
            'Privatna kupaonica',
            'Kada ili tuš',
            'Besplatni toaletni pribor',
            'Ogrtač i papuče',
            'Fen',
            'Klima uređaj',
            'Zaseban klima uređaj',
            'Besplatni WiFi',
            'TV s ravnim ekranom',
            'Satelitski programi',
            'Dnevni boravak',
            'Prostor za sjedenje',
            'Kauč na rasklapanje',
            'Radni stol',
            'Drveni ili parketni pod',
            'Mreža protiv komaraca',
            'Povezane sobe',
            'Vanjski namještaj',
            'Popločano dvorište',
            'Grijanje',
            'Gornji katovi dostupni stepenicama',
            'Zabranjeno pušenje',
          ],
          amenitiesEn: [
            'Balcony',
            'Sea view',
            'Garden view',
            'City view',
            'Kitchenette',
            'Stovetop',
            'Kitchenware',
            'Fridge',
            'Electric kettle',
            'Dining area',
            'Dining table',
            'Private bathroom',
            'Bath or shower',
            'Free toiletries',
            'Bathrobe and slippers',
            'Hairdryer',
            'Air conditioning',
            'Individual air conditioning',
            'Free WiFi',
            'Flat-screen TV',
            'Satellite channels',
            'Living room',
            'Seating area',
            'Sofa bed',
            'Desk',
            'Hardwood or parquet floor',
            'Mosquito net',
            'Interconnected rooms available',
            'Outdoor furniture',
            'Patio',
            'Heating',
            'Upper floors accessible by stairs only',
            'No smoking',
          ],
          heroImage: '/images/vila-ines/528894444.jpg',
          gallery: [
            '/images/vila-ines/528894444.jpg',
            '/images/vila-ines/582271891.jpg',
            '/images/vila-ines/582272087.jpg',
            '/images/vila-ines/883427780.jpg',
          ],
        },
      ],
    },
  ];

  getAll(): RentalUnit[] {
    return this.units;
  }

  getById(id: string): RentalUnit | undefined {
    return this.units.find((u) => u.id === id);
  }

  getRoomById(unitId: string, roomId: string) {
    const unit = this.getById(unitId);
    if (!unit) return undefined;
    const room = unit.rooms.find((r) => r.id === roomId);
    return room ? { unit, room } : undefined;
  }
}
